-- ============================================================================
-- DevSu — Script de Base de Datos
-- ============================================================================
-- Este proyecto usa el patrón "Database per Service": cada microservicio tiene
-- su propia base de datos PostgreSQL, físicamente separada.
-- Este script es para crear el esquema manualmente si no se usa Docker
--
-- Alternativa: el esquema también se puede generar/aplicar automáticamente
-- con las migraciones de Entity Framework Core (ver README.md, sección
-- "Despliegue" — comandos `dotnet ef database update`). Este script fue
-- generado a partir de esas mismas migraciones (`dotnet ef migrations
-- script`), no escrito a mano — así que ambos caminos producen el mismo
-- esquema.
-- ============================================================================

-- ============================================================================
-- 1) DEVSU.CLIENTS — ejecutar conectado a la base de datos "devsu_clients"
-- ============================================================================
-- Entidades: Person (base) / Client
-- Person y Client comparten la misma clave primaria (person_id / client_id)
-- ============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE persons (
    person_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    gender character varying(20) NOT NULL,
    age integer NOT NULL,
    identification_number character varying(20) NOT NULL,
    address character varying(250) NOT NULL,
    phone_number character varying(20) NOT NULL,
    CONSTRAINT "PK_persons" PRIMARY KEY (person_id)
);

CREATE TABLE clients (
    client_id integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_clients" PRIMARY KEY (client_id),
    CONSTRAINT fk_clients_persons_person_id FOREIGN KEY (client_id) REFERENCES persons (person_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_persons_identification_number ON persons (identification_number);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260913031639_InitialCreate', '10.0.12');

COMMIT;


-- ============================================================================
-- 2) DEVSU.ACCOUNTS — ejecutar conectado a la base de datos "devsu_accounts"
-- ============================================================================
-- Entidades: Account (raíz del agregado) / Movement (hijo, inmutable).
-- accounts.client_id/client_name son una referencia LÓGICA
-- al microservicio de Clients — SIN Foreign Key física, a propósito. 
-- Se sincronizan vía evento asíncrono (RabbitMQ se va a intentar).
-- ============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE accounts (
    account_number character varying(20) NOT NULL,
    account_type character varying(20) NOT NULL,
    initial_balance numeric(18,2) NOT NULL,
    is_active boolean NOT NULL,
    client_id integer NOT NULL,
    client_name character varying(150) NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (account_number)
);

CREATE TABLE movements (
    movement_id integer GENERATED BY DEFAULT AS IDENTITY,
    movement_date date NOT NULL,
    movement_type character varying(20) NOT NULL,
    amount numeric(18,2) NOT NULL,
    balance numeric(18,2) NOT NULL,
    account_number character varying(20) NOT NULL,
    CONSTRAINT pk_movements PRIMARY KEY (movement_id),
    CONSTRAINT fk_movements_accounts_account_number FOREIGN KEY (account_number) REFERENCES accounts (account_number) ON DELETE CASCADE
);

CREATE INDEX ix_movements_account_number ON movements (account_number);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260913114609_InitialCreate', '10.0.12');

COMMIT;
