-- ============================================================================
-- 1) DEVSU.CLIENTS — ejecutar conectado a la base de datos "devsu_clients"
-- ============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE persons (
    person_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    gender character varying(20) NOT NULL,
    age integer NOT NULL,
    identification_number character varying(20) NOT NULL,
    address character varying(250) NOT NULL,
    phone_number character varying(20) NOT NULL,
    CONSTRAINT "PK_persons" PRIMARY KEY (person_id)
);

CREATE TABLE clients (
    client_id integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_clients" PRIMARY KEY (client_id),
    CONSTRAINT fk_clients_persons_person_id FOREIGN KEY (client_id) REFERENCES persons (person_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_persons_identification_number ON persons (identification_number);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260913031639_InitialCreate', '10.0.12');

COMMIT;

START TRANSACTION;
ALTER TABLE persons ALTER COLUMN gender TYPE character varying(1);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260913215154_ChangeGenderToEnum', '10.0.12');

COMMIT;

-- ============================================================================
-- 2) DEVSU.ACCOUNTS — ejecutar conectado a la base de datos "devsu_accounts"
-- ============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE accounts (
    account_number character varying(20) NOT NULL,
    account_type character varying(20) NOT NULL,
    initial_balance numeric(18,2) NOT NULL,
    is_active boolean NOT NULL,
    client_id integer NOT NULL,
    client_name character varying(150) NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (account_number)
);

CREATE TABLE known_clients (
    client_id integer NOT NULL,
    name character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_known_clients PRIMARY KEY (client_id)
);

CREATE TABLE movements (
    movement_id integer GENERATED BY DEFAULT AS IDENTITY,
    movement_date date NOT NULL,
    movement_type character varying(20) NOT NULL,
    amount numeric(18,2) NOT NULL,
    balance numeric(18,2) NOT NULL,
    account_number character varying(20) NOT NULL,
    CONSTRAINT pk_movements PRIMARY KEY (movement_id),
    CONSTRAINT fk_movements_accounts_account_number FOREIGN KEY (account_number) REFERENCES accounts (account_number) ON DELETE CASCADE
);

CREATE INDEX ix_movements_account_number ON movements (account_number);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260913220601_InitialCreate', '10.0.12');

COMMIT;

