services:
  clients-api:
    build:
      context: .
      dockerfile: Devsu.Clients/src/Api/Dockerfile
    container_name: devsu-clients-api
    environment:
      ConnectionStrings__ClientsDb: ${CLIENTS_DB_CONNECTION}
      RabbitMq__Host: rabbitmq
      RabbitMq__User: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5047:8080"
    depends_on:
      - postgres
      - rabbitmq
      
  accounts-api:
    build:
      context: .
      dockerfile: Devsu.Accounts/src/Api/Dockerfile
    container_name: devsu-accounts-api
    environment:
      ConnectionStrings__AccountsDb: ${ACCOUNTS_DB_CONNECTION}
      RabbitMq__Host: rabbitmq
      RabbitMq__User: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5004:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:17
    container_name: devsu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: devsu_clients
    ports:
      - "5432:5432"
    volumes:
      - devsu_postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      
  rabbitmq:
    image: rabbitmq:4-management
    container_name: devsu-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  devsu_postgres_data: