services:
  postgres:
    image: postgres:17
    container_name: devsu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: devsu_clients
    ports:
      - "5432:5432"
    volumes:
      - devsu_postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      
  rabbitmq:
    image: rabbitmq:4-management
    container_name: devsu-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  devsu_postgres_data: